[12.0][ADD] user see only maintenance team where he is join in
OCA/maintenance pull request #107
Opened 2020-09-23 08:36 UTC by Borruso

Add ir.rule which it will be able to see only maintenance team where user is join in

2020-09-23 09:18 UTC, astirpe requested changes
Thanks for this PR.
Only a minor request to adopt the conventions as per the OCA guidelines.

2020-09-23 09:18 UTC, astirpe commented on base_maintenance_group/security/maintenance_security.xml
> +    <record model="ir.rule" id="only_subscribe_maintenance_team">
Please place `id` attribute before `model`, as stated in https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#xml-files:


```suggestion
    <record id="only_subscribe_maintenance_team" model="ir.rule">
```

2020-09-23 09:26 UTC, jarroyomorales commented
Hi @Borruso! I dont see any problem in being able to see other teams in the company. I may be interesting for some reason.

2020-09-23 09:38 UTC, Borruso commented
Could I have to make rule as well for version 13.0 ??

2020-09-23 09:42 UTC, astirpe commented
> Could I have to make rule as well for version 13.0 ??

Let's see if this PR is accepted a merged first. In case, after merged, you could create a new PR with the porting to V13.

2020-09-24 15:53 UTC, dalonsod commented
> Hi @Borruso! I dont see any problem in being able to see other teams in the company. It may be interesting for some reason.

@Borruso maybe this rule could be added within a `<data noupdate="1">` section. And IMO you should create another rule to grant total access for the `Full Access` group.

2020-09-25 10:58 UTC, dalonsod requested changes

2020-09-25 10:58 UTC, dalonsod commented on base_maintenance_group/security/maintenance_security.xml
> +            <field name="domain_force">[(1, 'in', 1)]</field>
This would not work:
```suggestion
            <field name="domain_force">[(1, '=', 1)]</field>
```

2020-09-25 18:00 UTC, dalonsod approved these changes
Tested on runbot 👍 
Not blocking, I only suggest a cosmetic change: for better understanding of `maintenance_security.xml` file after these changes: the already existing records should be placed under a `<data noupdate="0">` section

2020-09-25 18:02 UTC, marcelsavegnago approved these changes
LGTM

2020-09-28 09:31 UTC, etobella approved these changes

2020-09-28 09:57 UTC, dalonsod commented
> Not blocking, I only suggest a cosmetic change: for better understanding of `maintenance_security.xml` file after these changes: the already existing records should be placed under a `<data noupdate="0">` section

Maybe I've not explained this well. The suggested change should be keep `<data noupdate="1">` for the recently added rules and include `<data noupdate="0">` for the previous code (the `res.groups` records), in order to make the code more readable. @etobella are you agree?

2020-09-28 10:06 UTC, Borruso commented
> > Not blocking, I only suggest a cosmetic change: for better understanding of `maintenance_security.xml` file after these changes: the already existing records should be placed under a `<data noupdate="0">` section
> 
> Maybe I've not explained this well. The suggested change should be keep `<data noupdate="1">` for the recently added rules and include `<data noupdate="0">` for the previous code (the `res.groups` records), in order to make the code more readable. @etobella do you agree?

Sorry, I didn't understand. Should I wait @etobella or not?

2020-09-28 10:07 UTC, dalonsod commented
@etobella approved your recent changes, thus I'd wait for him

2020-09-28 10:28 UTC, etobella requested changes
Follow @dalonsod comments, It is just cosmetic but easier to understand. Also, I saw the noupdate and it should be 1, not 0 on the rule, as we could make a change there. If you want, you could create the data on a migration script in order to be sure that are created, but make them unactive on the creation as we don't want to break the old logic.

2020-09-28 10:28 UTC, etobella commented on base_maintenance_group/security/maintenance_security.xml
> +    <data noupdate="0">
Sorry, noupdate should be 1, as usual on record rules

2020-09-28 15:09 UTC, dalonsod approved these changes
:+1:

2020-09-28 15:31 UTC, etobella commented
If you update the module, you will not get the new rules on your system, maybe you need a migration script in order to add them

2020-09-28 15:34 UTC, etobella commented
Here you can check an example:
https://github.com/OCA/community-data-files/blob/12.0/account_payment_unece/migrations/12.0.1.0.0/post-migration.py#L7

2020-10-15 15:37 UTC, etobella commented
@Borruso Have you checked?

2020-10-15 16:14 UTC, Borruso commented
> @Borruso Have you checked?

@etobella I checked and I understand that even though the rules are in noupdate, no migration script is needed since these rules do not exist in the system, the problem shows up when the rules already existed in the system and I changed, for example, name or domain

2020-11-05 09:22 UTC, etobella approved these changes
You are right! Tested locally, when upgrading, the rules are created

2020-11-05 16:17 UTC, marcelsavegnago approved these changes

2020-11-09 11:07 UTC, Borruso commented
@astirpe could you check if your change request is ok?

2020-11-09 11:23 UTC, astirpe approved these changes
Code review ok. Not tested.

2020-11-17 09:47 UTC, etobella commented
/ocabot merge minor

2020-11-17 10:07 UTC, merged