[ADD] maintenance_equipment_always_fold
OCA/maintenance pull request #123
Opened 2020-12-18 17:25 UTC by lmiguens-solvos

Equipment categories will always be folded if I indicate it with an always_fold Boolean; if not, let him behave as before

2020-12-18 17:54 UTC, dalonsod requested changes
See travis and codecov

2020-12-18 17:54 UTC, dalonsod commented on maintenance_equipment_always_fold/__manifest__.py
> +    "version": "12.0.1.2.0",
Wrong version

2020-12-18 17:54 UTC, dalonsod commented on maintenance_equipment_always_fold/models/maintenance.py
> +    @api.one
Deprecated, please remove it

2020-12-18 17:54 UTC, dalonsod commented on maintenance_equipment_always_fold/__manifest__.py
> +    "demo": [
Maybe some demo data could be added

2020-12-21 11:04 UTC, lmiguens-solvos commented on maintenance_equipment_always_fold/__manifest__.py
> +    "demo": [
Done

2020-12-21 11:04 UTC, lmiguens-solvos commented on maintenance_equipment_always_fold/models/maintenance.py
> +    @api.one
Done

2020-12-21 11:04 UTC, lmiguens-solvos commented on maintenance_equipment_always_fold/__manifest__.py
> +    "version": "12.0.1.2.0",
New version put

2020-12-21 15:13 UTC, lmiguens-solvos commented
@etobella, @dalonsod, can you review this PR? Thanks.

2020-12-22 12:17 UTC, dalonsod approved these changes
Tested on runbot 👍 
Not blocking, `always_fold` field could be added to equipment categories tree view.

2020-12-26 23:59 UTC, marcelsavegnago approved these changes
LGTM

2020-12-30 08:09 UTC, dalonsod commented
hello @etobella is this PR ready to be merged? Thanks!!

2020-12-30 08:30 UTC, etobella commented
/ocabot merge nobump

2020-12-30 09:05 UTC, merged