14.0 [MIG] maintenance_equipment_hierarchy
OCA/maintenance pull request #144
Opened 2021-08-19 09:43 UTC by mariadforgeflow

Standard migration to v14

2021-08-19 16:17 UTC, dalonsod requested changes
See comments. Anyway, I'm not sure why isn't passing runbot, could you check?

2021-08-19 16:17 UTC, dalonsod commented on maintenance_equipment_hierarchy/__manifest__.py
> +    "version": "14.0.1.0.1",
Wrong version:
```suggestion
    "version": "14.0.1.0.0",
```

2021-08-19 16:17 UTC, dalonsod commented on maintenance_equipment_hierarchy/models/maintenance_equipment.py
> +        track_visibility="onchange",
This should be also changed in v13, as I've noticed:
```suggestion
        tracking=True,
```

2021-08-20 08:18 UTC, dalonsod approved these changes
👍 Tested on runbot

2021-08-21 11:05 UTC, flotho approved these changes
tested on runbot,

LGTM

2021-09-07 08:19 UTC, etobella approved these changes

2021-09-07 08:19 UTC, etobella commented
/ocabot merge nobump

2021-09-07 08:40 UTC, merged