[11.0][ADD] maintenance_equipment_sequence
OCA/maintenance pull request #18
Opened 2019-07-24 06:49 UTC by ageficent

This module introduces a sequence to the maintenance equipment managed from the maintenance equipment category.

User can create a sequence from the category specifying the prefix and next number, then equipment created belonging to this category will be assigned the next sequence number. 

cc ~ @Eficent

2019-07-24 14:17 UTC, astirpe requested changes

2019-07-24 14:17 UTC, astirpe commented on maintenance_equipment_sequence/models/maintenance.py
> +    code = fields.Char(
You are using this field as a default value for the sequence, in case the sequence is automatically created. So the field name is misleading.

Should be named 'Default Sequence Prefix', or similar.

2019-07-24 14:17 UTC, astirpe commented on maintenance_equipment_sequence/models/maintenance.py
> +    sequence_number_next = fields.Integer(
Also this field is used as a default for the sequence. Would be nice to find a better name for it?

2019-07-24 14:17 UTC, astirpe commented on maintenance_equipment_sequence/models/maintenance.py
> +            'name': vals['name'],
Reproduced in Runbot:

- Edit an existing category and add a value in Sequence Prefix.
- Save.

Result:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/maintenance/maintenance_equipment_sequence/models/maintenance.py", line 80, in write
    vals.update({'sequence_id': self.sudo()._create_sequence(vals).id})
  File "/home/odoo/build/OCA/maintenance/maintenance_equipment_sequence/models/maintenance.py", line 33, in _create_sequence
    'name': vals['name'],
KeyError: 'name'

```

2019-07-24 14:17 UTC, astirpe commented on maintenance_equipment_sequence/models/maintenance.py
> +                self.sequence_id._get_number_next_actual()
Trying in Runbot: adding a sequence in the category seems not updating the Next Number. Could you check?

2019-07-24 14:17 UTC, astirpe commented on maintenance_equipment_sequence/models/maintenance.py
> +        size=5,
The size here should be removed because is cutting the generated code.

For example:

In the category add a sequence with:
- "Sequence Size" = 4
- "Next Number" = 7
- "Prefix" = aaa

Create a new equipment with the above category. Save.

Result:

The equipment has code "aaa00" instead of "aaa0007".

2019-07-24 14:17 UTC, astirpe commented on maintenance_equipment_sequence/models/maintenance.py
> +        size=5,
I don't think a size should be specified here.

2019-07-24 14:17 UTC, astirpe commented on maintenance_equipment_sequence/models/maintenance.py
> +    )
Reproduced in Runbot:

Open an existing category that has already a sequence attached: the code value here is not displayed.

Could it be confusing?

2019-07-25 06:21 UTC, ageficent commented
@astirpe thanks for the review! I think I have attended all your comments, could you check and update the review. Thanks :+1:

2019-07-25 07:43 UTC, astirpe commented
Travis fails

2019-07-25 10:43 UTC, ageficent commented
> Travis fails

Yeah, my bad. Fixed now :green_apple:

2019-07-25 12:14 UTC, AaronHForgeFlow approved these changes
It works fine.

Not blocking, but I miss the sequence to show in equipment's views. I think it makes sense to modify the _name_get method to include the sequence.

2019-07-25 15:21 UTC, AaronHForgeFlow approved these changes
:+1: 

Good idea, better a view than modifying name_get

2019-07-26 06:37 UTC, astirpe commented
Travis is red:


```
ERROR: test_01_maintenance_equipment_sequence (odoo.addons.maintenance_equipment_sequence.tests.test_maintenance_equipment_sequence.TestMaintenanceEquipmentSequence)
` Create equipment category and check sequence has been automatically created, create equipments inside category and check sequence number has been set
Traceback (most recent call last):
`   File "/home/travis/odoo-11.0/odoo/models.py", line 4408, in ensure_one
`     _id, = self._ids
` ValueError: not enough values to unpack (expected 1, got 0)
`
` During handling of the above exception, another exception occurred:
`
` Traceback (most recent call last):
`   File "/home/travis/build/OCA/maintenance/maintenance_equipment_sequence/tests/test_maintenance_equipment_sequence.py", line 25, in test_01_maintenance_equipment_sequence
`     'sequence_number_next': 1,
`   File "/home/travis/build/OCA/maintenance/maintenance_equipment_sequence/models/maintenance.py", line 80, in create
`     self._compute_equipment_code()
`   File "/home/travis/build/OCA/maintenance/maintenance_equipment_sequence/models/maintenance.py", line 101, in _compute_equipment_code
`     self.ensure_one()
`   File "/home/travis/odoo-11.0/odoo/models.py", line 4411, in ensure_one
`     raise ValueError("Expected singleton: %s" % self)
` ValueError: Expected singleton: maintenance.equipment.category()
```

2019-07-26 07:22 UTC, ageficent commented
> Travis is red:

Fixed now green_apple

2019-08-01 15:40 UTC, LoisRForgeFlow approved these changes
Tested locally, looks good :+1:

2019-08-01 15:40 UTC, lreficent commented
@astirpe is this ok for you now?

2019-08-05 07:10 UTC, astirpe requested changes
There is a problem: when calculating the code of all the existing equipments belonging to a category, the code is increased by two instead of one. The result is that the equipments are numbered as #xyz0002, #xyz0004, #xyz0006, #xyz0008, etc...

2019-08-05 14:39 UTC, jbeficent commented
@astirpe thanks for reporting. This should be fixed now.

2019-09-27 09:46 UTC, astirpe commented
Would be nice if you can increase the tests coverage.

Also would be nice if you can fix this pylint waning: 
`maintenance_equipment_sequence/views/maintenance_views.xml:1: [W7908(missing-newline-extrafiles), ]  Missing newline
`

2019-11-06 09:19 UTC, jarroyomorales approved these changes
Code review LGTM! :+1:  Can you attend @astirpe 's comment and see if we can merge it?

2019-11-06 13:01 UTC, astirpe approved these changes

2019-11-06 13:01 UTC, astirpe commented
/ocabot merge

2019-11-06 14:11 UTC, jbeficent commented
/ocabot merge

2019-11-06 14:42 UTC, merged