[ADD] maintenance_plan module
OCA/maintenance pull request #2
Opened 2017-06-09 07:38 UTC by grindtildeath

2017-06-09 07:59 UTC, dreispt commented
LGTM; please fix TravisCI

Suggestions/questions
- It would be nice to have an action/button on "Equipment" to "Generate Next Maintenance"; the corresponding method would reused by the cron job.
- Wouldn't month duration be better for the maintenance intervals? Either way, it could be a nice addition to also have a duration UoM selector - "Days" or "Months".

2017-06-09 09:28 UTC, grindtildeath commented
@dreispt 
Thanks for your suggestions.

- We didn't code the 'Generate next maintenance' button as it would be used only at the creation of a new plan and the idea was to create all the maintenance plans and then run the ir.cron manually, should the requests be generated before it runs automatically. 
- A duration UoM could also be useful, but we wanted to keep it as simple as possible to begin with. 

IMO both could be nice addition to the module, but I don't have time to spend on these features at the moment.

2017-06-09 09:54 UTC, dreispt commented
@grindtildeath That's why I mentioned them as suggestion ideas.

2017-06-09 11:04 UTC, dreispt commented
Does this have any conflict with the standard module's planned maintenance generation, if both are configured?
Does it disable it or will both will work?

Or from a user PoV:
 have planned maintenance configured on my Equipments, and I then install this. 
What is the impact and what do I need to take care to get everything right?

2017-06-16 10:11 UTC, grindtildeath commented
@dreispt 
I added a post-init hook, with the description in README.rst of what will happen and what should be done before installing should the standard feature already bu used.
Feel free to let me know what could be improved.

2017-08-11 13:54 UTC, dreispt reviewed
LGTM but made a few comements

2017-08-11 13:54 UTC, dreispt commented on maintenance_plan/models/maintenance.py
> +    def _cron_generate_requests(self):
If this is to be used by a Cron it is an external API, so the name method should not start with an underscore.
Furthermore, I can see this used in a Button somewhere, so I suggest renaming it to "do_generate_requests" and expand the docstring to explain that ii can bu used by a cron job.

2017-08-11 13:54 UTC, dreispt commented on maintenance_plan/views/maintenance.xml
> +        <field name="arch" type="xml">
This view is redundant - Odoo does name searches by default.

2017-08-11 13:54 UTC, dreispt commented on maintenance_plan/models/maintenance.py
> +            'name': _('Preventive Maintenance (%s) - %s') %
Please extract the dict creation into it's own `_prepare_new_maintenance_request` method, so that it is easy to extend it.

2017-08-14 08:53 UTC, grindtildeath commented on maintenance_plan/models/maintenance.py
> +    def _cron_generate_requests(self):
Thanks for your review. 
However, as this method is called by standard ir.cron from maintenance module, I suppose it's better to leave its name as it is, so we don't have to update the existing ir.cron : 
https://github.com/odoo/odoo/blob/10.0/addons/maintenance/data/maintenance_cron.xml#L10

2017-08-16 12:37 UTC, dreispt commented on maintenance_plan/models/maintenance.py
> +    def _cron_generate_requests(self):
I see, OK then.

2017-08-16 12:39 UTC, dreispt approved these changes

2017-08-16 13:23 UTC, elicoidal requested changes
some details and one question on contraint

2017-08-16 13:23 UTC, elicoidal commented on maintenance_plan/__manifest__.py
> + 'version': '10.0.1.0.0',
a summary would be welcome

2017-08-16 13:23 UTC, elicoidal commented on maintenance_plan/hooks.py
> +                    "action to install the module."))
Nice to have: indicate which record are faulty

2017-08-16 13:23 UTC, elicoidal commented on maintenance_plan/models/maintenance.py
> +         "Maintenance kind name already exists !")]
remove exclamation mark

2017-08-16 13:23 UTC, elicoidal commented on maintenance_plan/models/maintenance.py
> +                # If the gap between the last_maintenance_done and the
This look like specific rule that might not apply everywhere

2017-08-16 13:23 UTC, elicoidal commented on maintenance_plan/models/maintenance.py
> +         "equipment maintenance plan!")]
please remove exclamation mark.

2017-08-17 15:22 UTC, grindtildeath commented on maintenance_plan/models/maintenance.py
> +                # If the gap between the last_maintenance_done and the
@elicoidal Thanks for your review.

This code is an adaptation from odoo to keep the behaviour as close as possible to standard module : https://github.com/odoo/odoo/blob/10.0/addons/maintenance/models/maintenance.py#L165

2017-08-22 15:31 UTC, dreispt commented
@elicoidal can you review the changes please?

2017-10-02 14:47 UTC, grindtildeath commented
@elicoidal @pedrobaeza Can we merge this ?

2017-10-02 16:49 UTC, pedrobaeza approved these changes
@elicoidal's concern is answered, so I approve this and merge. Thanks all.

2017-10-02 16:49 UTC, merged