[14.0][ADD] maintenance_product: New adon.
OCA/maintenance pull request #217
Opened 2022-03-15 08:22 UTC by victoralmau

This module links *Maintenance Equipments* and *Products*, easing creation in this ways

Please @pedrobaeza and @CarlosRoca13  can you review it?

@Tecnativa TT33410

2022-03-15 08:40 UTC, pedrobaeza requested changes

2022-03-15 08:40 UTC, pedrobaeza commented on maintenance_product/models/maintenance_equipment.py
> +        to product ones"""
Proper PEP257 docstring is:

```suggestion
        """If product is set, equipment name, seller, seller ref and cost defaults
        to product ones.
        """
```

2022-03-15 08:40 UTC, pedrobaeza commented on maintenance_product/readme/DESCRIPTION.rst
> +This module links *Maintenance Equipments* and *Products*, easing creation in this ways
```suggestion
This module links *Maintenance Equipments* and *Products*, easing creation of new equipments.
```

2022-03-15 08:40 UTC, pedrobaeza commented on maintenance_product/readme/USAGE.rst
> +* Go to *Maintenance > Configuration > Equipment Categories* and create a new one (or modify an existing one) filling in the new field *Product Category*.
Incorrect RST syntax: Leave one empty line in between (the same for the rest).

2022-03-15 08:40 UTC, pedrobaeza commented on maintenance_product/tests/test_maintenance_product.py
> +        self.equipment._onchange_product_id()
Use here `Form` instead (and in the rest of onchanges)

2022-03-15 08:40 UTC, pedrobaeza commented on maintenance_product/readme/CONTRIBUTORS.rst
> +  * Pedro M. Baeza
Give credits to César

2022-03-15 18:12 UTC, pedrobaeza approved these changes

2022-03-15 19:08 UTC, etobella commented
If youbwant tonease the creation, wouldn't have more sense to create the equipment from a purchase?

2022-03-16 08:57 UTC, victoralmau commented
> If youbwant tonease the creation, wouldn't have more sense to create the equipment from a purchase?

Perhaps what you indicate would be a different new addon, in this case, without the need for any purchase, you want to link an equipment to a product.

2022-03-16 09:54 UTC, etobella commented
I understand the goal of your module, i just asked if it had sense my comment. In my case, we buy equipments but sometimes the product is the same for several versions, as they share the same functionality. Price, supplier and all extra fields are taken from the purchase order. Also equipment is generated on confirmation, as you may need the record before it is received(preparation of spaces...)
I understand this is much more complex. I asked if it had sense to join both ideas somehow

2022-03-16 13:02 UTC, victoralmau commented
Ok, thanks for the explanation. Yes, I think it would be a useful use case but I think it should be a new addon called: `maintenance_purchase` that has this as a dependency to be able to create the equipment from the purchase order. What do you think @pedrobaeza ?

2022-03-16 13:08 UTC, pedrobaeza commented
Yeah, it's not a bad flow, but we need to ask our customer if they follow such flow.

2022-03-28 17:10 UTC, pedrobaeza commented
@etobella we are keeping this flow for now. The other module may be added in the future.

Let's merge it:

/ocabot merge nobump

2022-03-28 17:16 UTC, merged