[11.0][add] maintenance_equipment_hierarchy
OCA/maintenance pull request #24
Opened 2019-08-05 13:17 UTC by jbeficent

This module allows to manage a hierarchy of equipments.

![image](https://user-images.githubusercontent.com/7683926/62467467-21b40700-b794-11e9-953d-a6dfe839520b.png)

![image](https://user-images.githubusercontent.com/7683926/62467483-2aa4d880-b794-11e9-9231-6ae7ff307b01.png)

2019-08-05 13:18 UTC, jbeficent commented
cc @nuriamartinxifre @ceeficent

2019-08-06 09:17 UTC, astirpe requested changes
In the equipment tree view or when searching equipments, the hierarchy is not displayed. Did you consider to define a def name_get() method?

_________



As improvement of the UX, I would move the field "Parent Equipment" at the top of the form (before "Equipment Category" or before "Name")

_________

Tested in Runbot:

- Open an already existing Equipment (eg.: A)
- click on button "Children"
- Create a new Equipment (eg.: B)

Result:
- B is created but is not a child of A

Expected:
- B is created as child of A

2019-08-09 13:48 UTC, astirpe commented
Needs to be rebased to fix travis.

2019-08-27 09:32 UTC, lreficent commented
Rebase done.

2019-10-04 11:54 UTC, dalonsod commented on maintenance_equipment_hierarchy/views/maintenance_equipment_views.xml
> +            <field name="location" position="before">
As @astirpe recommended, the code could be

```
            <field name="category_id" position="before">
                <field name="parent_id" readonly="context.get('readonly_parent_id', False)"/>
            </field>

```

2019-10-04 11:54 UTC, dalonsod commented on maintenance_equipment_hierarchy/models/maintenance_equipment.py
> +            'context': self.env.context,
As @astirpe recommended, the code could be

```
            'context': {
                **self.env.context,
                'default_parent_id': self.id,
                'readonly_parent_id': True},

```

2019-10-29 16:50 UTC, dalonsod commented on maintenance_equipment_hierarchy/models/maintenance_equipment.py
> +            'context': self.env.context,
@jbeficent @lreficent will you resume with this PR? If not, I'd continue with it

2019-11-11 08:16 UTC, dalonsod commented
Superseded by #39

2019-11-11 09:44 UTC, astirpe commented
@jbeficent is it okay for you to continue with the other PR and close this one?

2019-11-13 15:39 UTC, closed without merging