[13.0][IMP] maintenance_plan: Add Generate preventive maintenance requests button from plan view form.
OCA/maintenance pull request #292
Opened 2023-02-17 08:05 UTC by victoralmau

Add Generate preventive maintenance requests button from plan view form

Add button from maintenance plan to allow generate maintenance requests without waiting for cron.

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT41729

2023-02-17 08:14 UTC, pedrobaeza requested changes

2023-02-17 08:14 UTC, pedrobaeza commented on maintenance_plan/models/maintenance_plan.py
> +    def action_generate_preventive_maintenance_requests(self):
```suggestion
    def button_manual_request_generation(self):
```

2023-02-17 08:14 UTC, pedrobaeza commented on maintenance_plan/models/maintenance_plan.py
> +        """Call the cron method that will generate the equipment requests."""
```suggestion
        """Call the same method that the cron for generating manually the maintenance requests."""
```

2023-02-17 08:14 UTC, pedrobaeza commented on maintenance_plan/views/maintenance_plan_views.xml
> +                        string="Generate preventive maintenance requests"
```suggestion
                        string="Generate requests for current threshold"
                        help="If not clicked, the scheduled action will do it for you."
```

2023-02-17 08:14 UTC, pedrobaeza commented on maintenance_plan/views/maintenance_plan_views.xml
> +                        class="oe_highlight"
No highlight, please. This is not the option to follow.

```suggestion
```

2023-02-17 08:35 UTC, victoralmau commented
Changes done.

2023-02-21 12:10 UTC, victoralmau commented
Rebase done.

2023-02-21 12:24 UTC, pedrobaeza approved these changes

2023-02-21 12:36 UTC, CarlosRoca13 approved these changes
Code review

2023-02-21 13:11 UTC, pedrobaeza commented
/ocabot merge minor

2023-02-21 13:19 UTC, merged