[14.0][FIX] maintenance_account /maintenance_purchase: check before creation
OCA/maintenance pull request #309
Opened 2023-03-01 11:59 UTC by etobella

This fixes a bug when you create equipments from a purchase/invoice with two lines, with products with the same category but it was not used before. Two identical categories would have been created.

2023-03-01 12:57 UTC, victoralmau requested changes
Thank you, can you improve the tests to check that this does not happen in the future?

2023-03-01 12:57 UTC, victoralmau commented on maintenance_account/models/account_move.py
> +            category = category_model.create(self._prepare_equipment_category_vals())
```suggestion
```

2023-03-03 08:03 UTC, victoralmau requested changes
Reviewing this in detail I see that the problem is the depends, this would be the change in v15: https://github.com/OCA/maintenance/pull/312/commits/bceba8dca1407bbbe89d8505c57f4ca68e7e299d

In `maintenance_purchase` the change would be similar.

2023-03-03 08:05 UTC, pedrobaeza commented
Please don't do that. If you put such depends, and you change any equipment in the product category, it will recompute all the past moves.

2023-03-03 08:15 UTC, victoralmau commented
> Please don't do that. If you put such depends, and you change any equipment in the product category, it will recompute all the past moves.

Ok, I have changed the approach in https://github.com/OCA/maintenance/pull/312

2023-03-03 08:17 UTC, pedrobaeza commented on maintenance_account/models/account_move.py
> +            category = category_model.create(self._prepare_equipment_category_vals())
This one is duplicated, isn't it?

2023-03-04 18:28 UTC, pedrobaeza commented
@etobella please resolve conflicts and remove the duplicated creation for proceeding with the merge.

2023-03-06 18:26 UTC, pedrobaeza approved these changes
/ocabot merge patch

2023-03-06 18:30 UTC, merged