[FIX] maintenance_plan: Use language on cron creation
OCA/maintenance pull request #360
Opened 2023-09-23 22:02 UTC by etobella

Without this change, we might have problems when creating the request as data might differ from what you write (for example, if we come from a copied record).

Issued is raised because cron are executed with no lang.

The problems comes from using a field that is translatable

2023-09-25 06:47 UTC, pedrobaeza commented
It's weird to use sometimes the maintenance plan name and other times the equipment name.

2023-09-25 07:22 UTC, etobella commented
I understand your concerns, but it is already being used, I am not sure if we should change the behavior directly...

2023-09-25 07:27 UTC, pedrobaeza commented
Yes, I think it can be improved. Maybe a compose name between equipment name and a "suffix"?

2023-10-16 13:10 UTC, etobella commented
But the maintenance request final name will be as you ask:
`_("Preventive Maintenance (%s) - %s") % (kind, description)`
where kind is used to split the kind of preventive request we are setting.  And description will be the name.

2023-10-16 14:10 UTC, pedrobaeza commented
OK, as you prefer

2024-03-20 01:32 UTC, mamcode requested changes
Looks good, thank you.

2024-03-20 01:33 UTC, mamcode approved these changes

2024-03-20 07:02 UTC, etobella commented
/ocabot merge patch

2024-03-20 07:06 UTC, merged