[11.0][ADD] maintenance_request_sequence
OCA/maintenance pull request #41
Opened 2019-11-13 12:56 UTC by jarroyomorales

Adds a sequence field to maintenance requests.

2019-11-13 13:15 UTC, jbeficent commented
@jarroyomorales Sometimes a company may want to maintain different sequences, depending on the `maintenance.kind`. I think that it could be a good idea to allow a user to create a sequence in this model, that would then be used when creating a maintenance request that used this kind.

Look how it's done in the `product_sequence` module https://github.com/OCA/product-attribute/blob/11.0/product_sequence/models/product_category.py

2019-11-13 13:40 UTC, jarroyomorales commented
@jbeficent I thought about that, it is the same than in `maintenance_equipment_sequence` if I'm not wrong.  At first my idea was to create a sequence per team, but it would cause problems when changing the team of the requests. 
I also have problems understanding the usage of kind. I thought it was like a category field to group similar requests, but demo data's examples are 'Weekly' and 'Monthly', which confuses me, since I wouldnt group requests by it's frecuency, it is more interesting to group them by the type of actions they will require or something like that. Maybe the only problem is that demo data is not the best.
Another thing is that kind is not a required field in requests, which sequence would they get? Should we make the field required? Also, maybe a user creates a request and then a technician assigns the kind, so the sequence can't be decided on creation.

2019-11-13 13:49 UTC, jbeficent commented
@jarroyomorales I agree that the examples of `maintenance.kind` are very confusing. I never use them as 'weekly', or 'monthly', but I use values like:
* Customer complaint
* Internal problem
* Planned maintenance
....

In the end it is the only way to categorize maintenance requests.

2019-11-13 15:13 UTC, etobella commented
> In the end it is the only way to categorize maintenance requests.

Well, we can create something like tags in order to categorize, as it would be more helpful, sometimes, maintenance requests could fulfill more than one kind (outside of this module, obviously)

Using Kinds is a bad choice IMO, the module is not related to `maintenance_plan` and kind is not required and can be changed, What happens if we create a MR in a kind and then we change it? Do we need to change the code?

2019-11-13 15:23 UTC, etobella commented
Maybe the best options would be to use team as the selector of the sequence and we can maintain the old code if we change the team, at the end we want to know the change of team.

2019-11-13 16:59 UTC, jarroyomorales commented
@etobella Now it works how you said, let's see what others think.

2019-11-13 21:24 UTC, etobella requested changes
I think you missed to add a file :wink:

2019-11-13 21:24 UTC, etobella commented on maintenance_request_sequence/models/maintenance_request.py
> +        names1 = super(models.Model, self).name_search(
just super().name_search is enough

2019-11-13 21:24 UTC, etobella commented on maintenance_request_sequence/views/maintenance_request.xml
> +            <field name="owner_user_id" position="before">
Wouldn't be better to add it on the top of the request?

2019-11-14 16:09 UTC, jarroyomorales commented
@etobella Comments attended!

2019-11-18 16:37 UTC, etobella approved these changes
LGTM :+1:

2019-12-04 08:29 UTC, jarroyomorales commented
@jbeficent @ageficent What do you think about this?

2019-12-04 16:42 UTC, JordiBForgeFlow approved these changes
:+1: Technical and functional review.

2019-12-04 16:42 UTC, jbeficent commented
/ocabot merge

2019-12-04 17:04 UTC, merged