[16.0][IMP] maintenance_equipment_sequence: remove duplicated field
OCA/maintenance pull request #438
Opened 2024-12-17 08:11 UTC by ThiagoMForgeFlow

The serial number field is duplicated in the equipment tree view. 

@ForgeFlow

2024-12-17 09:19 UTC, LoisRForgeFlow approved these changes
Thanks!

2024-12-17 10:25 UTC, TelmoSuarez requested changes
This doesn't remove duplicated field, only hides it, maybe use position="move"?

2024-12-17 10:52 UTC, ThiagoMForgeFlow commented
> This doesn't remove duplicated field, only hides it, maybe use position="move"?

Thanks for the advice

2024-12-17 11:33 UTC, etobella approved these changes

2024-12-18 12:19 UTC, LoisRForgeFlow commented
@TelmoSuarez could you update your review?

2024-12-18 14:17 UTC, TelmoSuarez approved these changes

2024-12-18 14:45 UTC, LoisRForgeFlow commented
@etobella merge? :)

2024-12-18 14:58 UTC, etobella commented
/ocabot merge patch

2024-12-18 15:02 UTC, merged

2024-12-19 08:38 UTC, LoisRForgeFlow commented
@ThiagoMForgeFlow could you fwport if needed?