[10.0][ADD] Module maintenance_settings
OCA/maintenance pull request #5
Opened 2017-06-20 11:52 UTC by espo-tony

This module doesn't introduce new functionalities; it rather provides maintenance-related generic tools to be used in further specific-purpose modules, including security groups and configuration settings section.

2017-06-20 11:59 UTC, espo-tony commented
@dreispt 
Can I ask you to review this PR? The goal is not to provide new functionalities but to introduce some generic tool (like the maintenance configuration settings and domain-specific security groups) to be used in further modules.
Something like we discussed in #4 
Thank you in advance.

2017-06-20 12:09 UTC, pedrobaeza commented
As it's a base module without functionality itself, then you should prefix it with `base_`, and avoid plurals (check https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules). Then my suggestion is `base_maintenance_config`.

2017-06-20 12:15 UTC, espo-tony commented
@pedrobaeza 
Thank you for the suggestion. You're right, indeed. I renamed the module

2017-07-24 13:10 UTC, astirpe requested changes

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/README.rst
> +   :target: http://www.gnu.org/licenses/agpl-3.0-standalone.html
According with the updated template, this line should be:
```
   :target: http://www.gnu.org/licenses/agpl
```

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/README.rst
> +Configuration
Remove empty sections

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/README.rst
> +
Add this line:

```
Do not contact contributors directly about support or help with technical issues.
```

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/__init__.py
> +# Copyright 2017 Onestein (<http://www.onestein.eu>)
Remove copyright in __init__.py files

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/models/__init__.py
> +# Copyright 2017 Onestein (<http://www.onestein.eu>)
Remove copyright in __init__.py files

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/menuitems.xml
> +        <record model="ir.ui.menu" id="maintenance.menu_maintenance_configuration">
The `id` definition must precede the `model`, as stated in the OCA guidelines

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/views/maintenance_config_settings.xml
> +    <data>
`<data>` could be removed

2017-07-24 13:10 UTC, astirpe commented on base_maintenance_config/menuitems.xml
> +    <data>
`<data>` could be removed

2017-07-24 13:23 UTC, astirpe requested changes

2017-07-24 13:23 UTC, astirpe commented on base_maintenance_config/README.rst
> +Bugs are tracked on `GitHub Issues
Replace `account-financial-tools` with `maintenance` in this link

2017-07-24 13:23 UTC, astirpe commented on base_maintenance_config/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/92/10.0
Replace id 92 with the one for maintenance

2017-07-24 13:43 UTC, astirpe approved these changes

2017-07-24 15:24 UTC, mreficent commented on base_maintenance_config/__manifest__.py
> +    'website': 'http://www.onestein.eu',
`https://github.com/OCA/maintenance`

2017-07-25 09:24 UTC, MiquelRForgeFlow approved these changes
LGTM :+1:

2017-08-22 16:48 UTC, dreispt approved these changes

2017-08-22 16:48 UTC, merged