[12.0][MIG] maintenance_equipment_tags
OCA/maintenance pull request #75
Opened 2020-02-24 12:42 UTC by jarroyomorales

Standard migration, no changes.

@etobella  @NuriaMForgeFlow  @dalonsod

2020-02-24 12:47 UTC, etobella approved these changes
LGTM :+1: No major changes

2020-02-24 13:06 UTC, dalonsod requested changes
See comment.

The module has no demo data, could you add it?

Also functionally tested, LGTM

2020-02-24 13:06 UTC, dalonsod commented on maintenance_equipment_tags/views/maintenance_equipment_tag.xml
> +                    <group>
Consider add a `name` attribute for further extensions of this view

2020-02-24 14:03 UTC, NuriaXifre approved these changes
LGTM! Functional review.

2020-02-24 15:48 UTC, jarroyomorales commented
@dalonsod Comments attended!

2020-02-24 16:10 UTC, dalonsod approved these changes
👍

2020-02-25 08:28 UTC, etobella commented
/ocabot merge

2020-02-25 08:29 UTC, etobella requested changes
Check version

2020-02-25 08:31 UTC, etobella approved these changes

2020-02-25 08:46 UTC, etobella commented
/ocabot merge
Now the version is fine :wink:

2020-02-25 09:06 UTC, merged