[12.0][MIG] maintenance_equipment_contract
OCA/maintenance pull request #86
Opened 2020-04-16 14:20 UTC by jarroyomorales

Migration to 12.0 of maintenance_equipment_contract.
`'account.analytic.account'` became `contract.contract` so a few changes were needed.

@etobella  @dalonsod

2020-04-16 21:32 UTC, etobella approved these changes
LGTM 👍

2020-04-20 06:35 UTC, dalonsod requested changes
Tested on runbot, only a functional doubt and pending squash commits

2020-04-20 06:35 UTC, dalonsod commented on maintenance_equipment_contract/views/maintenance_equipment.xml
> +                        icon="fa-usd" type="object" attrs="{'invisible': [('contract_ids', '=', [])]}">
With this invisible condition, you cannot create a contract from equipment form, when the equipment hasn't any contract yet, you need to yo to Invoicing menu to achieve it. But, if it has got one or more contracts, creating a contract ithin an equipment is already enabled. Maybe this button should be always visible. What do you think?

2020-04-20 07:59 UTC, jarroyomorales commented
@dalonsod Yes, I agree with you, just made it always visible to be more consistent. Thank you for the review!

2020-04-20 08:30 UTC, dalonsod approved these changes
LGTM 👍 
Don't forget to squash commits

2020-04-20 09:53 UTC, etobella commented
/ocabot merge

2020-04-20 09:53 UTC, etobella commented
/ocabot merge nobump

2020-04-20 10:21 UTC, merged