[IMP] base_maintenance: Add a Maintenance Request Report
OCA/maintenance pull request #97
Opened 2020-07-16 13:58 UTC by marcelsavegnago

2020-07-16 14:09 UTC, etobella approved these changes
LGTM

2020-07-16 14:26 UTC, etobella commented
Review Travis linting

2020-07-30 21:36 UTC, etobella commented
@marcelsavegnago Can you try to install locally the pre-commit and then apply the changes? This way it will resolve automatically your linting problems. It will only works on 13.0 and over, but it is a huge step.

https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97
https://github.com/OCA/maintainer-quality-tools#qa-tools-for-odoo-maintainers-mqt

2020-08-19 03:12 UTC, marcelsavegnago commented
@etobella Done. Thank you for your help and I'm sorry for doing this just now. For the past few days I have been working on client projects and Brazilian localization modules and unfortunately the time is short: D

2020-08-19 03:16 UTC, marcelsavegnago commented
@dalonsod @lmiguens-solvos Can you review this PR ? please :)

2020-08-19 07:18 UTC, dalonsod requested changes
Only cosmetic changes

2020-08-19 07:18 UTC, dalonsod commented on base_maintenance/readme/CONTRIBUTORS.rst
> +* Lois Rilo <lois.rilo@eficent.com>
Maybe @LoisRForgeFlow is not agree with this change XD

2020-08-19 07:18 UTC, dalonsod commented on base_maintenance/views/report_maintenance_request.xml
> +                            <strong>Equipament:</strong>
It's good time to fix this typo:
```suggestion
                            <strong>Equipment:</strong>
```

2020-08-21 16:33 UTC, marcelsavegnago commented on base_maintenance/readme/CONTRIBUTORS.rst
> +* Lois Rilo <lois.rilo@eficent.com>
@dalonsod So, what do you think of not changing that? Or better already change?

2020-08-21 16:34 UTC, marcelsavegnago commented on base_maintenance/readme/CONTRIBUTORS.rst
> +* Lois Rilo <lois.rilo@eficent.com>
@LoisRForgeFlow What do you think ?

2020-08-22 12:03 UTC, etobella commented on base_maintenance/readme/CONTRIBUTORS.rst
> +* Lois Rilo <lois.rilo@eficent.com>
I can answer for him, eficent was the name of the company, but it has recently changed for forgeflow, so keep forgeflow please :wink:

2020-08-25 09:07 UTC, dalonsod commented on base_maintenance/readme/CONTRIBUTORS.rst
> +* Lois Rilo <lois.rilo@eficent.com>
@marcelsavegnago don't forget to undo this change

2020-09-14 08:44 UTC, jarroyomorales approved these changes
LGTM!

2020-09-15 09:09 UTC, jarroyomorales commented
@dalonsod Can you check again so it can get merged?

2020-09-15 09:36 UTC, dalonsod commented
@marcelsavegnago `CONTRIBUTORS.rst` file is still wrong, as @etobella said https://github.com/OCA/maintenance/pull/97#discussion_r475083583

2020-09-15 15:14 UTC, marcelsavegnago commented
@dalonsod done.

2020-09-15 15:44 UTC, dalonsod approved these changes

2020-09-15 16:36 UTC, etobella commented
Just one last comment, con you change the commit message of the last commit, I know this is purely visual, but it is in order to maintain some homogeneity. Then we can proceed with the merge :wink:

2020-09-15 18:06 UTC, marcelsavegnago commented
@etobella Done.

2020-09-16 13:10 UTC, etobella commented
/ocabot merge minor

2020-09-16 14:00 UTC, merged